version: 2.1
jobs:
  deploy:
    docker:
      - image: node:18.20.5
    steps:
    - checkout
    - run:
        name: Install zcatalyst-cli
        command: npm install -g zcatalyst-cli@beta
    - run:
        name: Install dependencies and deploy
        command: |
          cd functions/alien_city_function
          npm install
          cd ../..
          catalyst deploy
workflows:
  version: 2
  build:
    jobs:
      - deploy